angka1 = float(input("Masukkan angka ke 1 = "))
angka2 = float(input("Masukkan angka ke 2 = "))
angka3 = float(input("Masukkan angka ke 3 = "))
angka4 = float(input("Masukkan angka ke 4 = "))
angka5 = float(input("Masukkan angka ke 5 = "))
print(float((angka1+angka2+angka3+angka4+angka5)/2))
